/*
 SPDX-License-Identifier: AGPL-3.0-or-later

 Copyright (C) 2025 - 2026 emexlab

 This file is part of Nyxian.

 Nyxian is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Nyxian is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with Nyxian. If not, see <https://www.gnu.org/licenses/>.
*/

#include <LindChain/ProcEnvironment/Surface/libkern/patch.h>

/* libc API */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(open);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(close);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(dup);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(dup2);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(fcntl);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(realpath);

/* mmap API  */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mmap);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(munmap);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mprotect);

/* mach VM API */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_allocate);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_deallocate);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_protect);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_inherit);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_map);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_remap);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_read);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_read_list);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_read_overwrite);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_write);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_copy);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_wire);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_msync);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_behavior_set);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_machine_attribute);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_purgable_control);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_region);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_region_recurse);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_page_info);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_page_query);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_page_range_query);

/* legacy VM API */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_allocate);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_deallocate);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_protect);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_inherit);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_map);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_remap);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_read);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_read_list);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_read_overwrite);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_write);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_copy);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_wire);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_msync);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_behavior_set);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_machine_attribute);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_purgable_control);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_region_64);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_region_recurse_64);

/* mach port API */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_allocate);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_deallocate);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_construct);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_extract_right);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_names);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_type);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_rename);               /* deprecated */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_allocate_name);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_allocate_qos);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_allocate_full);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_destroy);              /* deprecated */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_destruct);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_get_refs);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_mod_refs);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_insert_right);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_get_srights);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_peek);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_set_mscount);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_set_seqno);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_request_notification);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_get_set_status);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_move_member);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_insert_member);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_extract_member);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_get_attributes);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_set_attributes);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_get_context);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_set_context);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_guard);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_unguard);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_space_info);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_space_basic_info);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_dnrequest_info);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_kernel_object);

/* mach messaging API */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_msg);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_msg_overwrite);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_msg_trap);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_msg_overwrite_trap);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_msg_receive);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_msg_send);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_msg_destroy);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_msg_server);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_msg_server_once);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_msg_server_importance);

/* fileport API */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(fileport_makeport);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(fileport_makefd);
